
package com.mastermaq.integracrm;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "IntegraSalesForce", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://crmintegration.mastermaq.com.br/CrmIntegration/IntegraCrm.asmx?WSDL")
public class IntegraSalesForce
    extends Service
{

    private final static URL INTEGRASALESFORCE_WSDL_LOCATION;
    private final static WebServiceException INTEGRASALESFORCE_EXCEPTION;
    private final static QName INTEGRASALESFORCE_QNAME = new QName("http://tempuri.org/", "IntegraSalesForce");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://crmintegration.mastermaq.com.br/CrmIntegration/IntegraCrm.asmx?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        INTEGRASALESFORCE_WSDL_LOCATION = url;
        INTEGRASALESFORCE_EXCEPTION = e;
    }

    public IntegraSalesForce() {
        super(__getWsdlLocation(), INTEGRASALESFORCE_QNAME);
    }

    public IntegraSalesForce(WebServiceFeature... features) {
        super(__getWsdlLocation(), INTEGRASALESFORCE_QNAME, features);
    }

    public IntegraSalesForce(URL wsdlLocation) {
        super(wsdlLocation, INTEGRASALESFORCE_QNAME);
    }

    public IntegraSalesForce(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, INTEGRASALESFORCE_QNAME, features);
    }

    public IntegraSalesForce(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IntegraSalesForce(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IntegraSalesForceSoap
     */
    @WebEndpoint(name = "IntegraSalesForceSoap")
    public IntegraSalesForceSoap getIntegraSalesForceSoap() {
        return super.getPort(new QName("http://tempuri.org/", "IntegraSalesForceSoap"), IntegraSalesForceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IntegraSalesForceSoap
     */
    @WebEndpoint(name = "IntegraSalesForceSoap")
    public IntegraSalesForceSoap getIntegraSalesForceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "IntegraSalesForceSoap"), IntegraSalesForceSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (INTEGRASALESFORCE_EXCEPTION!= null) {
            throw INTEGRASALESFORCE_EXCEPTION;
        }
        return INTEGRASALESFORCE_WSDL_LOCATION;
    }

}
