
package com.mastermaq.integracrm;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IntegraSalesForceSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IntegraSalesForceSoap {


    /**
     * 
     * @param personalAuthentication
     * @param oportunidade
     * @return
     *     returns com.mastermaq.integracrm.RetornoOportunidade
     */
    @WebMethod(operationName = "NovaOportunidade", action = "http://tempuri.org/NovaOportunidade")
    @WebResult(name = "NovaOportunidadeResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "NovaOportunidade", targetNamespace = "http://tempuri.org/", className = "com.mastermaq.integracrm.NovaOportunidade")
    @ResponseWrapper(localName = "NovaOportunidadeResponse", targetNamespace = "http://tempuri.org/", className = "com.mastermaq.integracrm.NovaOportunidadeResponse")
    public RetornoOportunidade novaOportunidade(
        @WebParam(name = "oportunidade", targetNamespace = "http://tempuri.org/")
        Oportunidade oportunidade,
        @WebParam(name = "PersonalAuthentication", targetNamespace = "http://tempuri.org/", header = true, partName = "PersonalAuthentication")
        PersonalAuthentication personalAuthentication);

    /**
     * 
     * @param personalAuthentication
     * @param dataAtualizacao
     * @return
     *     returns com.mastermaq.integracrm.ArrayOfContaEL
     */
    @WebMethod(operationName = "EL_DadosContas", action = "http://tempuri.org/EL_DadosContas")
    @WebResult(name = "EL_DadosContasResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "EL_DadosContas", targetNamespace = "http://tempuri.org/", className = "com.mastermaq.integracrm.ELDadosContas")
    @ResponseWrapper(localName = "EL_DadosContasResponse", targetNamespace = "http://tempuri.org/", className = "com.mastermaq.integracrm.ELDadosContasResponse")
    public ArrayOfContaEL elDadosContas(
        @WebParam(name = "dataAtualizacao", targetNamespace = "http://tempuri.org/")
        String dataAtualizacao,
        @WebParam(name = "PersonalAuthentication", targetNamespace = "http://tempuri.org/", header = true, partName = "PersonalAuthentication")
        PersonalAuthentication personalAuthentication);

    /**
     * 
     * @param personalAuthentication
     * @param dataAtualizacao
     * @return
     *     returns com.mastermaq.integracrm.ArrayOfContatoEL
     */
    @WebMethod(operationName = "EL_DadosContatos", action = "http://tempuri.org/EL_DadosContatos")
    @WebResult(name = "EL_DadosContatosResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "EL_DadosContatos", targetNamespace = "http://tempuri.org/", className = "com.mastermaq.integracrm.ELDadosContatos")
    @ResponseWrapper(localName = "EL_DadosContatosResponse", targetNamespace = "http://tempuri.org/", className = "com.mastermaq.integracrm.ELDadosContatosResponse")
    public ArrayOfContatoEL elDadosContatos(
        @WebParam(name = "dataAtualizacao", targetNamespace = "http://tempuri.org/")
        String dataAtualizacao,
        @WebParam(name = "PersonalAuthentication", targetNamespace = "http://tempuri.org/", header = true, partName = "PersonalAuthentication")
        PersonalAuthentication personalAuthentication);

    /**
     * 
     * @param personalAuthentication
     * @param contato
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "EL_AtualizaDadosContato", action = "http://tempuri.org/EL_AtualizaDadosContato")
    @WebResult(name = "EL_AtualizaDadosContatoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "EL_AtualizaDadosContato", targetNamespace = "http://tempuri.org/", className = "com.mastermaq.integracrm.ELAtualizaDadosContato")
    @ResponseWrapper(localName = "EL_AtualizaDadosContatoResponse", targetNamespace = "http://tempuri.org/", className = "com.mastermaq.integracrm.ELAtualizaDadosContatoResponse")
    public String elAtualizaDadosContato(
        @WebParam(name = "contato", targetNamespace = "http://tempuri.org/")
        ContatoEL contato,
        @WebParam(name = "PersonalAuthentication", targetNamespace = "http://tempuri.org/", header = true, partName = "PersonalAuthentication")
        PersonalAuthentication personalAuthentication);

    /**
     * 
     * @param personalAuthentication
     * @return
     *     returns com.mastermaq.integracrm.ArrayOfProdutoSF
     */
    @WebMethod(operationName = "SF_ProdutoInfo", action = "http://tempuri.org/SF_ProdutoInfo")
    @WebResult(name = "SF_ProdutoInfoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SF_ProdutoInfo", targetNamespace = "http://tempuri.org/", className = "com.mastermaq.integracrm.SFProdutoInfo")
    @ResponseWrapper(localName = "SF_ProdutoInfoResponse", targetNamespace = "http://tempuri.org/", className = "com.mastermaq.integracrm.SFProdutoInfoResponse")
    public ArrayOfProdutoSF sfProdutoInfo(
        @WebParam(name = "PersonalAuthentication", targetNamespace = "http://tempuri.org/", header = true, partName = "PersonalAuthentication")
        PersonalAuthentication personalAuthentication);

    /**
     * 
     * @param personalAuthentication
     * @param dataAtualizacao
     * @return
     *     returns com.mastermaq.integracrm.ArrayOfOportunidadeSF
     */
    @WebMethod(operationName = "SF_OportunidadeInfo", action = "http://tempuri.org/SF_OportunidadeInfo")
    @WebResult(name = "SF_OportunidadeInfoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SF_OportunidadeInfo", targetNamespace = "http://tempuri.org/", className = "com.mastermaq.integracrm.SFOportunidadeInfo")
    @ResponseWrapper(localName = "SF_OportunidadeInfoResponse", targetNamespace = "http://tempuri.org/", className = "com.mastermaq.integracrm.SFOportunidadeInfoResponse")
    public ArrayOfOportunidadeSF sfOportunidadeInfo(
        @WebParam(name = "dataAtualizacao", targetNamespace = "http://tempuri.org/")
        String dataAtualizacao,
        @WebParam(name = "PersonalAuthentication", targetNamespace = "http://tempuri.org/", header = true, partName = "PersonalAuthentication")
        PersonalAuthentication personalAuthentication);

    /**
     * 
     * @param personalAuthentication
     * @param dataAtualizacao
     * @return
     *     returns com.mastermaq.integracrm.ArrayOfContaSF
     */
    @WebMethod(operationName = "SF_ContaInfo", action = "http://tempuri.org/SF_ContaInfo")
    @WebResult(name = "SF_ContaInfoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SF_ContaInfo", targetNamespace = "http://tempuri.org/", className = "com.mastermaq.integracrm.SFContaInfo")
    @ResponseWrapper(localName = "SF_ContaInfoResponse", targetNamespace = "http://tempuri.org/", className = "com.mastermaq.integracrm.SFContaInfoResponse")
    public ArrayOfContaSF sfContaInfo(
        @WebParam(name = "dataAtualizacao", targetNamespace = "http://tempuri.org/")
        String dataAtualizacao,
        @WebParam(name = "PersonalAuthentication", targetNamespace = "http://tempuri.org/", header = true, partName = "PersonalAuthentication")
        PersonalAuthentication personalAuthentication);

    /**
     * 
     * @param personalAuthentication
     * @param dataAtualizacao
     * @return
     *     returns com.mastermaq.integracrm.ArrayOfContatoSF
     */
    @WebMethod(operationName = "SF_ContatoInfo", action = "http://tempuri.org/SF_ContatoInfo")
    @WebResult(name = "SF_ContatoInfoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SF_ContatoInfo", targetNamespace = "http://tempuri.org/", className = "com.mastermaq.integracrm.SFContatoInfo")
    @ResponseWrapper(localName = "SF_ContatoInfoResponse", targetNamespace = "http://tempuri.org/", className = "com.mastermaq.integracrm.SFContatoInfoResponse")
    public ArrayOfContatoSF sfContatoInfo(
        @WebParam(name = "dataAtualizacao", targetNamespace = "http://tempuri.org/")
        String dataAtualizacao,
        @WebParam(name = "PersonalAuthentication", targetNamespace = "http://tempuri.org/", header = true, partName = "PersonalAuthentication")
        PersonalAuthentication personalAuthentication);

}
